---
# tasks file for python

- name: Setup_Debian | Download package information.
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Setup_Debian | Install required OS packages.
  ansible.builtin.apt:
    package: "{{ __python_os_packages }}"
    state: present
  become: true


- name: Setup_Debian | Install optional OS packages.
  block:

    - name: Setup_Debian | Install optional OS packages.
      ansible.builtin.apt:
        name: "{{ __python_optional_os_packages }}"
        state: present
      become: true

  rescue:

    - name: Setup_Debian | Continue without installing all optional packages.
      ansible.builtin.debug:
        msg: "Failed to install one or more optional OS packages."
